package com.zy.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.name
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.gibm
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    private String gibm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.userid
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.name
     *
     * @return the value of role.name
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.name
     *
     * @param name the value for role.name
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.gibm
     *
     * @return the value of role.gibm
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    public String getGibm() {
        return gibm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.gibm
     *
     * @param gibm the value for role.gibm
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    public void setGibm(String gibm) {
        this.gibm = gibm == null ? null : gibm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.userid
     *
     * @return the value of role.userid
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.userid
     *
     * @param userid the value for role.userid
     *
     * @mbggenerated Fri Apr 21 13:47:24 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    @Override
    public String toString() {
        return "Role{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", gibm='" + gibm + '\'' +
                ", userid=" + userid +
                '}';
    }
}